[tool.poetry]
name = "sureflap-api"
version = "4.2.5"
license = "Apache-2.0"
description = "SureFlap API is a simple, yet powerful RESTful API for products from Sure Petcare"
authors = ["Fabian Eulitz <dev@sustineo.de>"]
repository = "https://github.com/fabieu/sureflap-api"
keywords = ["Sureflap", "Sure Petcare", "REST", "API"]

[tool.poetry.dependencies]
python = "^3.10,<4.0"
cachetools = "^5.3.3"
fastapi = "^0.110.0"
uvicorn = "^0.29.0"
requests = "^2.31.0"
dynaconf = "^3.2.5"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
vermin = "^1.6.0"
autopep8 = "^2.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
